name: Build package
on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.7
    - name: Get latest dvc version
      id: latest
      shell: bash
      run: |
        version=$(./latest.sh)
        echo "::set-output name=version::$version"
    - name: Download dvc exe
      run: wget https://github.com/iterative/dvc/archive/dvc-${{ steps.latest.outputs.version }}.exe
    - name: Sign
      env:
        EXE_ITERATIVE_CERTIFICATE: ${{ secrets.EXE_ITERATIVE_CERTIFICATE }}
        EXE_ITERATIVE_CERTIFICATE_PASS: ${{ secrets.EXE_ITERATIVE_CERTIFICATE_PASS }}
      run: python sign.py dvc-${{ steps.latest.outputs.version }}.exe
