name: Build package
on:
  push:
    branches:
    - main
  pull_request: {}
  schedule:
    - cron: '0 0 * * *'
jobs:
  windows:
    environment: aws
    permissions:
      contents: read
      id-token: write
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Download dvc pkg
      run: python download.py
    - name: Install dvc requirements
      run: |
        pip install .\dvc[all]
        # https://github.com/iterative/dvc/issues/7949
        pip install PyInstaller==5.9.0
        # https://github.com/iterative/dvc/issues/9654
        pip install flufl-lock==7.1.1
        dvc doctor
    - name: Set pkg type
      shell: bash
      run: echo 'PKG = "exe"' > dvc/_build.py
    - name: Build binary
      run: python build_bin.py
    - name: Pull images
      run: dvc pull
    - name: Build package
      run: python build.py
    - name: Sign
      env:
        EXE_ITERATIVE_CERTIFICATE: ${{ secrets.EXE_ITERATIVE_CERTIFICATE }}
        EXE_ITERATIVE_CERTIFICATE_PASS: ${{ secrets.EXE_ITERATIVE_CERTIFICATE_PASS }}
      run: python sign.py dvc-*.exe
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::260760892802:role/dvc-public-exe-deployer
    - name: Upload
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: python upload.py dvc-*.exe
