name: Build package
on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.8
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Get latest dvc version
      id: latest
      shell: bash
      run: |
        version=$(./latest.sh)
        echo "::set-output name=version::$version"
    - name: Download dvc pkg
      run: python download.py
    - name: Install dvc requirements
      run: |
        pip install .\dvc[all]
        pip install -r dvc\scripts\build-requirements.txt
        gem install --no-document fpm
        dvc doctor
    - name: Build
      run: |
        dvc --cd dvc pull
        python dvc\scripts\build.py exe
    - name: Sign
      env:
        EXE_ITERATIVE_CERTIFICATE: ${{ secrets.EXE_ITERATIVE_CERTIFICATE }}
        EXE_ITERATIVE_CERTIFICATE_PASS: ${{ secrets.EXE_ITERATIVE_CERTIFICATE_PASS }}
      run: python sign.py dvc\scripts\innosetup\dvc-${{ steps.latest.outputs.version }}.exe
    - name: Upload
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: python upload.py dvc\scripts\innosetup\dvc-${{ steps.latest.outputs.version }}.exe
