name: Update package
on:
  push:
    branches: main
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: get latest dvc version
      id: latest
      shell: bash
      run: |
        version=$(./latest.sh)
        echo "::set-output name=version::$version"
    - name: try update
      id: update
      shell: bash
      run: |
        echo latest version ${{ steps.latest.outputs.version }}
        ./update.sh ${{ steps.latest.outputs.version }}
        echo "::set-output name=changes::$(git diff)"
    - name: create PR
      if: ${{ steps.update.outputs.changes != '' }}
      id: create-pr
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: dvc ${{ steps.latest.outputs.version }}
        title: dvc ${{ steps.latest.outputs.version }}
    - name: Merge the PR
      if: ${{ steps.update.outputs.changes != '' }}
      run: gh pr merge --squash --delete-branch ${{ steps.create-pr.outputs.pull-request-url }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
